###
# Prepare base
##
- name: Import secrets
  include_vars: "inventories/{{ deployment_environment }}/group_vars/filebeat_nodes/secrets.yml"
  no_log:       true

- name: Make directory for project
  file:
    path: "{{ filebeat_dir }}"
    owner: "{{ filebeat_user }}"
    group: "{{ filebeat_group }}"
    state: directory
    mode: "0755"
  become: "{{ become_root }}"

- name: Make directory for data
  file:
    path: "{{ filebeat_dir }}/data"
    owner: "root"
    group: "root"
    state: directory
    mode: "0777"
  become: "{{ become_root }}"

- name: Is config dirtectory exists?
  stat:
    path: "{{ filebeat_dir }}/config"
  register: is_config_dir

- name: Is data directory exists?
  stat:
    path: "{{ filebeat_dir }}/data"
  register: is_data_dir

- name: Change config directory ownership
  file:
    path: "{{ filebeat_dir }}/config"
    owner: "{{ filebeat_user }}"
    group: "{{ filebeat_group }}"
    state: directory
  when: is_config_dir.stat.exists
  become: "{{ become_root }}"

- name: Change data directory ownership
  file:
    path: "{{ filebeat_dir }}/data"
    owner: "root"
    group: "root"
    mode: "0777"
    state: directory
  when: is_data_dir.stat.exists
  become: "{{ become_root }}"
###


###
# Install Filebeat
##
- name: Sync docker project to remote machine
  synchronize:
    src: files/filebeat-docker/
    dest: "{{ filebeat_dir }}"
    recursive: yes
    rsync_path: "/usr/bin/rsync"
    use_ssh_args: yes
    perms: no
  become: "{{ become_root }}"

- name: Remove config_example
  file:
    path: "{{ filebeat_dir }}/config_example"
    state: absent

- name: Remove .env.example
  file:
    path: "{{ filebeat_dir }}/.env.example"
    state: absent

- name: Bring .env into project folder
  template:
    src: templates/.env.j2
    dest: "{{ filebeat_dir }}/.env"
    owner: "{{ filebeat_user }}"
    group: "{{ filebeat_group }}"
    mode: "0744"

- name: Bring Filebeat docker-compose.yml file
  template:
    src:   templates/docker-compose.yml.j2
    dest:  "{{ filebeat_dir }}/docker-compose.yml"
    owner: "{{ filebeat_user }}"
    group: "{{ filebeat_group }}"
    mode:  "0755"
  become: "{{ become_root }}"

- name: Bring Filebeat configuration yml file
  template:
    src: templates/filebeat.yml.j2
    dest: "{{ filebeat_dir }}/config/filebeat.yml"
    owner: "root"
    group: "root"
    mode: "0755"
  become: "{{ become_root }}"
###
