---
###
# Install ELK section
##
- hosts: ssl_nodes
  serial: 3
  gather_facts: false
  roles:
  - ssl
  tags:
  - ssl

- hosts: apm_server_nodes
  serial: 2
  gather_facts: false
  environment:
    http_proxy:  http://cloudproxy-t.nat.bt.com:8080
    https_proxy: http://cloudproxy-t.nat.bt.com:8080
  roles:
  - apm-server
  tags:
  - apm-server

- hosts: elastic_nodes
  serial: 3
  gather_facts: false
  environment:
    http_proxy:  http://cloudproxy-t.nat.bt.com:8080
    https_proxy: http://cloudproxy-t.nat.bt.com:8080
  roles:
  - elastic
  tags:
  - elastic

- hosts: filebeat_nodes
  serial: 3
  gather_facts: true
  environment:
    http_proxy:  http://cloudproxy-t.nat.bt.com:8080
    https_proxy: http://cloudproxy-t.nat.bt.com:8080
  roles:
  - filebeat
  tags:
  - filebeat

- hosts: kibana_nodes
  serial: 1
  gather_facts: false
  environment:
    http_proxy:  http://cloudproxy-t.nat.bt.com:8080
    https_proxy: http://cloudproxy-t.nat.bt.com:8080
  roles:
  - kibana
  tags:
  - kibana

- hosts: logstash_nodes
  serial: 1  
  gather_facts: false
  environment:
    http_proxy:  http://cloudproxy-t.nat.bt.com:8080
    https_proxy: http://cloudproxy-t.nat.bt.com:8080
  roles:
  - logstash
  tags:
  - logstash

- hosts: metricbeat_nodes
  serial: 3
  gather_facts: true
  environment:
    http_proxy:  http://cloudproxy-t.nat.bt.com:8080
    https_proxy: http://cloudproxy-t.nat.bt.com:8080
  roles:
  - metricbeat
  tags:
  - metricbeat
###


###
# Rolling upgrade section - would restart docker container
##
# Actual Elasticsearch
- hosts: elasticsearch_rolling_upgrade
  serial: 1
  gather_facts: false

  roles:
  - elasticsearch-rolling-upgrade
  tags:
  - elasticsearch-rolling-upgrade

# APM-Server, Filebeat, Kibana, Logstash & Metricbeat
- hosts: elk_rolling_upgrade
  serial: 6
  gather_facts: false

  roles:
  - elk-rolling-upgrade
  tags:
  - elk-rolling-upgrade
###


###
# Full scale upgrade section - would restart all docker containers simultaneously 
##
- hosts: elasticsearch_full_upgrade
  serial: 6
  gather_facts: false

  roles:
  - elasticsearch-full-upgrade
  tags:
  - elasticsearch-full-upgrade
###


###
#  Deploy Elasticsearch Index Templates & ILM Policies
##
- hosts: elastic_templates
  serial: 1
  gather_facts: false

  roles:
    - elastic-templates
  tags:
  - elastic-templates
###
