- name: Make directory for saved objects
  file:
    path:  "{{ kibana_dir }}/saved-objects/ops-space"
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    state: directory
    mode:  "0755"
  become: "{{ become_root }}"

- name: "[OPS Space] Bring Saved Objects onto the box first"
  synchronize:
    src:          files/saved-objects/ops-space
    dest:         "{{ kibana_dir }}/saved-objects/"
    recursive:    yes
    rsync_path:   "/usr/bin/rsync"
    use_ssh_args: yes
  become: "{{ become_root }}"
# ===========================


- name: "[OPS Space] Find path to Advanced Settings Object ndjson files"
  find:
    paths:    "{{ kibana_dir }}/saved-objects/ops-space/advanced-settings"
    recurse:  yes
    patterns: '*.ndjson'
  register: ops_view_advanced_settings_paths
  when: import_ops_ad_settings

- name: "[OPS Space] Find path to Dashboard Object ndjson files"
  find:
    paths:    "{{ kibana_dir }}/saved-objects/ops-space/dashboards"
    recurse:  yes
    patterns: '*.ndjson'
  register: ops_view_dashboards_paths
  when: import_ops_dashboards

- name: "[OPS Space] Find path to Data View Object ndjson files"
  find:
    paths:    "{{ kibana_dir }}/saved-objects/ops-space/data-views"
    recurse:  yes
    patterns: '*.ndjson'
  register: ops_view_data_views_paths
  when: import_ops_data_views

- name: "[OPS Space] Find path to Index Pattern Object ndjson files"
  find:
    paths:    "{{ kibana_dir }}/saved-objects/ops-space/index-patterns"
    recurse:  yes
    patterns: '*.ndjson'
  register: ops_view_index_patterns_paths
  when: import_ops_index_patterns

- name: "[OPS Space] Find path to Kibana Tag Object ndjson files"
  find:
    paths:    "{{ kibana_dir }}/saved-objects/ops-space/kibana-tags"
    recurse:  yes
    patterns: '*.ndjson'
  register: ops_view_kibana_tags_paths
  when: import_ops_kibana_tags

- name: "[OPS Space] Find path to Visualisation Object ndjson files"
  find:
    paths:    "{{ kibana_dir }}/saved-objects/ops-space/visualisations"
    recurse:  yes
    patterns: '*.ndjson'
  register: ops_view_visualisations_paths
  when: import_ops_visualisations
# ===========================


# Import OPS-View Saved Object
- name: "[OPS Space] Import Saved Advanced Settings into Kibana OPS-View Space"
  shell:  'curl --cacert /configdata/kibana-docker/ssl/ca.crt --noproxy "*" -XPOST "{{ kibana_server_public_base_url }}/s/{{ item.space_id }}/api/saved_objects/_import?overwrite=true" -H "kbn-xsrf: true" --form file=@"{{ item.path }}" -K- <<< "--user {{ kibana_super_username }}:{{ kibana_super_password }}"'
  vars:
    space_ids:
      - ops-view
  with_items: "[{% for space_id in space_ids %}{% for file in ops_view_advanced_settings_paths.files %}{ 'path': '{{ file.path }}', 'space_id': '{{ space_id }}' }{% if not loop.last %},{% endif %}{% endfor %}{% if not loop.last %},{% endif %}{% endfor %}]"
  when: import_ops_ad_settings

- name: "[OPS Space] Import Saved Dashboards into Kibana OPS-View Space"
  shell:  'curl --cacert /configdata/kibana-docker/ssl/ca.crt --noproxy "*" -XPOST "{{ kibana_server_public_base_url }}/s/{{ item.space_id }}/api/saved_objects/_import?overwrite=true" -H "kbn-xsrf: true" --form file=@"{{ item.path }}" -K- <<< "--user {{ kibana_super_username }}:{{ kibana_super_password }}"'
  vars:
    space_ids:
      - ops-view
  with_items: "[{% for space_id in space_ids %}{% for file in ops_view_dashboards_paths.files %}{ 'path': '{{ file.path }}', 'space_id': '{{ space_id }}' }{% if not loop.last %},{% endif %}{% endfor %}{% if not loop.last %},{% endif %}{% endfor %}]"
  when: import_ops_dashboards

- name: "[OPS Space] Import Saved Data Views into Kibana OPS-View Space"
  shell:  'curl --cacert /configdata/kibana-docker/ssl/ca.crt --noproxy "*" -XPOST "{{ kibana_server_public_base_url }}/s/{{ item.space_id }}/api/saved_objects/_import?overwrite=true" -H "kbn-xsrf: true" --form file=@"{{ item.path }}" -K- <<< "--user {{ kibana_super_username }}:{{ kibana_super_password }}"'
  vars:
    space_ids:
      - ops-view
  with_items: "[{% for space_id in space_ids %}{% for file in ops_view_data_views_paths.files %}{ 'path': '{{ file.path }}', 'space_id': '{{ space_id }}' }{% if not loop.last %},{% endif %}{% endfor %}{% if not loop.last %},{% endif %}{% endfor %}]"
  when: import_ops_data_views

- name: "[OPS Space] Import Saved Index Patterns into Kibana OPS-View Space"
  shell:  'curl --cacert /configdata/kibana-docker/ssl/ca.crt --noproxy "*" -XPOST "{{ kibana_server_public_base_url }}/s/{{ item.space_id }}/api/saved_objects/_import" -H "kbn-xsrf: true" --form file=@"{{ item.path }}" -K- <<< "--user {{ kibana_super_username }}:{{ kibana_super_password }}"'
  vars:
    space_ids:
      - ops-view
  with_items: "[{% for space_id in space_ids %}{% for file in ops_view_index_patterns_paths.files %}{ 'path': '{{ file.path }}', 'space_id': '{{ space_id }}' }{% if not loop.last %},{% endif %}{% endfor %}{% if not loop.last %},{% endif %}{% endfor %}]"
  when: import_ops_index_patterns

- name: "[OPS Space] Import Saved Tags into Kibana OPS-View Space"
  shell:  'curl --cacert /configdata/kibana-docker/ssl/ca.crt --noproxy "*" -XPOST "{{ kibana_server_public_base_url }}/s/{{ item.space_id }}/api/saved_objects/_import" -H "kbn-xsrf: true" --form file=@"{{ item.path }}" -K- <<< "--user {{ kibana_super_username }}:{{ kibana_super_password }}"'
  vars:
    space_ids:
      - ops-view
  with_items: "[{% for space_id in space_ids %}{% for file in ops_view_kibana_tags_paths.files %}{ 'path': '{{ file.path }}', 'space_id': '{{ space_id }}' }{% if not loop.last %},{% endif %}{% endfor %}{% if not loop.last %},{% endif %}{% endfor %}]"
  when: import_ops_kibana_tags

- name: "[OPS Space] Import Saved Visualisations into Kibana OPS-View Space"
  shell:  'curl --cacert /configdata/kibana-docker/ssl/ca.crt --noproxy "*" -XPOST "{{ kibana_server_public_base_url }}/s/{{ item.space_id }}/api/saved_objects/_import" -H "kbn-xsrf: true" --form file=@"{{ item.path }}" -K- <<< "--user {{ kibana_super_username }}:{{ kibana_super_password }}"'
  vars:
    space_ids:
      - ops-view
  with_items: "[{% for space_id in space_ids %}{% for file in ops_view_visualisations_paths.files %}{ 'path': '{{ file.path }}', 'space_id': '{{ space_id }}' }{% if not loop.last %},{% endif %}{% endfor %}{% if not loop.last %},{% endif %}{% endfor %}]"
  when: import_ops_visualisations
# ===========================


# Now we can delete Saved Objects from the remote machine to save space (and because they not needed there)
- name: "[OPS Space] Delete all Saved Objects from the box (cause they were imported)"
  file:
    path: "{{ kibana_dir }}/saved-objects"
    state: absent
# ===========================
