- name: Make directory for saved objects
  file:
    path:  "{{ kibana_dir }}/saved-objects/radius-space"
    owner: "{{ kibana_user }}"
    group: "{{ kibana_group }}"
    state: directory
    mode:  "0755"
  become: "{{ become_root }}"

- name: "[Radius Space] Bring Saved Objects onto the box first"
  synchronize:
    src:          files/saved-objects/radius-space
    dest:         "{{ kibana_dir }}/saved-objects/"
    recursive:    yes
    rsync_path:   "/usr/bin/rsync"
    use_ssh_args: yes
  become: "{{ become_root }}"


- name: "[Radius Space] Find path to Advanced Settings Object ndjson files"
  find:
    paths:    "{{ kibana_dir }}/saved-objects/radius-space/advanced-settings"
    recurse:  yes
    patterns: '*.ndjson'
  register: radius_view_advanced_settings_paths
  when: import_radius_ad_settings

- name: "[Radius Space] Find path to Dashboard Object ndjson files"
  find:
    paths:    "{{ kibana_dir }}/saved-objects/radius-space/dashboards"
    recurse:  yes
    patterns: '*.ndjson'
  register: radius_view_dashboards_paths
  when: import_radius_dashboards

- name: "[Radius Space] Find path to Index Pattern Object ndjson files"
  find:
    paths:    "{{ kibana_dir }}/saved-objects/radius-space/data-views"
    recurse:  yes
    patterns: '*.ndjson'
  register: radius_view_data_views_paths
  when: import_radius_data_views

- name: "[Radius Space] Find path to Index Pattern Object ndjson files"
  find:
    paths:    "{{ kibana_dir }}/saved-objects/radius-space/index-patterns"
    recurse:  yes
    patterns: '*.ndjson'
  register: radius_view_index_patterns_paths
  when: import_radius_index_patterns

- name: "[Radius Space] Find path to Kibana Tag Object ndjson files"
  find:
    paths:    "{{ kibana_dir }}/saved-objects/radius-space/kibana-tags"
    recurse:  yes
    patterns: '*.ndjson'
  register: radius_view_kibana_tags_paths
  when: import_radius_kibana_tags

- name: "[Radius Space] Find path to Visualisation Object ndjson files"
  find:
    paths:    "{{ kibana_dir }}/saved-objects/radius-space/visualisations"
    recurse:  yes
    patterns: '*.ndjson'
  register: radius_view_visualisations_paths
  when: import_radius_visualisations
# ===========================


# Import RADIUS-View Saved Object
- name: "[Radius Space] Import Saved Advanced Settings into Kibana RADIUS-View Space"
  shell:  'curl --cacert /configdata/kibana-docker/ssl/ca.crt --noproxy "*" -XPOST "{{ kibana_server_public_base_url }}/s/{{ item.space_id }}/api/saved_objects/_import?overwrite=true" -H "kbn-xsrf: true" --form file=@"{{ item.path }}" -K- <<< "--user {{ kibana_super_username }}:{{ kibana_super_password }}"'
  vars:
    space_ids:
      - radius-view
  with_items: "[{% for space_id in space_ids %}{% for file in radius_view_advanced_settings_paths.files %}{ 'path': '{{ file.path }}', 'space_id': '{{ space_id }}' }{% if not loop.last %},{% endif %}{% endfor %}{% if not loop.last %},{% endif %}{% endfor %}]"
  when: import_radius_ad_settings

- name: "[Radius Space] Import Saved Dashboards into Kibana RADIUS-View Space"
  shell:  'curl --cacert /configdata/kibana-docker/ssl/ca.crt --noproxy "*" -XPOST "{{ kibana_server_public_base_url }}/s/{{ item.space_id }}/api/saved_objects/_import?overwrite=true" -H "kbn-xsrf: true" --form file=@"{{ item.path }}" -K- <<< "--user {{ kibana_super_username }}:{{ kibana_super_password }}"'
  vars:
    space_ids:
      - radius-view
  with_items: "[{% for space_id in space_ids %}{% for file in radius_view_dashboards_paths.files %}{ 'path': '{{ file.path }}', 'space_id': '{{ space_id }}' }{% if not loop.last %},{% endif %}{% endfor %}{% if not loop.last %},{% endif %}{% endfor %}]"
  when: import_radius_dashboards

- name: "[Radius Space] Import Saved Data Views into Kibana RADIUS-View Space"
  shell:  'curl --cacert /configdata/kibana-docker/ssl/ca.crt --noproxy "*" -XPOST "{{ kibana_server_public_base_url }}/s/{{ item.space_id }}/api/saved_objects/_import?overwrite=true" -H "kbn-xsrf: true" --form file=@"{{ item.path }}" -K- <<< "--user {{ kibana_super_username }}:{{ kibana_super_password }}"'
  vars:
    space_ids:
      - radius-view
  with_items: "[{% for space_id in space_ids %}{% for file in radius_view_data_views_paths.files %}{ 'path': '{{ file.path }}', 'space_id': '{{ space_id }}' }{% if not loop.last %},{% endif %}{% endfor %}{% if not loop.last %},{% endif %}{% endfor %}]"
  when: import_radius_data_views

- name: "[Radius Space] Import Saved Index Patterns into Kibana RADIUS-View Space"
  shell:  'curl --cacert /configdata/kibana-docker/ssl/ca.crt --noproxy "*" -XPOST "{{ kibana_server_public_base_url }}/s/{{ item.space_id }}/api/saved_objects/_import" -H "kbn-xsrf: true" --form file=@"{{ item.path }}" -K- <<< "--user {{ kibana_super_username }}:{{ kibana_super_password }}"'
  vars:
    space_ids:
      - radius-view
  with_items: "[{% for space_id in space_ids %}{% for file in radius_view_index_patterns_paths.files %}{ 'path': '{{ file.path }}', 'space_id': '{{ space_id }}' }{% if not loop.last %},{% endif %}{% endfor %}{% if not loop.last %},{% endif %}{% endfor %}]"
  when: import_radius_index_patterns

- name: "[Radius Space] Import Saved Tags into Kibana RADIUS-View Space"
  shell:  'curl --cacert /configdata/kibana-docker/ssl/ca.crt --noproxy "*" -XPOST "{{ kibana_server_public_base_url }}/s/{{ item.space_id }}/api/saved_objects/_import" -H "kbn-xsrf: true" --form file=@"{{ item.path }}" -K- <<< "--user {{ kibana_super_username }}:{{ kibana_super_password }}"'
  vars:
    space_ids:
      - radius-view
  with_items: "[{% for space_id in space_ids %}{% for file in radius_view_kibana_tags_paths.files %}{ 'path': '{{ file.path }}', 'space_id': '{{ space_id }}' }{% if not loop.last %},{% endif %}{% endfor %}{% if not loop.last %},{% endif %}{% endfor %}]"
  when: import_radius_kibana_tags

- name: "[Radius Space] Import Saved Visualisations into Kibana RADIUS-View Space"
  shell:  'curl --cacert /configdata/kibana-docker/ssl/ca.crt --noproxy "*" -XPOST "{{ kibana_server_public_base_url }}/s/{{ item.space_id }}/api/saved_objects/_import" -H "kbn-xsrf: true" --form file=@"{{ item.path }}" -K- <<< "--user {{ kibana_super_username }}:{{ kibana_super_password }}"'
  vars:
    space_ids:
      - radius-view
  with_items: "[{% for space_id in space_ids %}{% for file in radius_view_visualisations_paths.files %}{ 'path': '{{ file.path }}', 'space_id': '{{ space_id }}' }{% if not loop.last %},{% endif %}{% endfor %}{% if not loop.last %},{% endif %}{% endfor %}]"
  when: import_radius_visualisations
# ===========================


# Now we can delete Saved Objects from the remote machine to save space (and because they not needed there)
- name: "[Radius Space] Delete Saved Objects from the box (cause they were imported)"
  file:
    path: "{{ kibana_dir }}/saved-objects"
    state: absent
# ===========================
