###
# Prepare base
##
- name: Import secrets
  include_vars: "inventories/{{ deployment_environment }}/group_vars/elastic_templates/secrets.yml"
  no_log:       true

- name: Import secrets
  include_vars: "inventories/{{ deployment_environment }}/group_vars/elastic_nodes/vars.yml"
  no_log:       true
###


###
# Import Security Role Mappings
##
- name: Import Security Role Mappings
  uri: 
    url:              "https://{{ elastic_publish_host }}:61116/_security/role_mapping/{{ item.mapping_name }}"
    use_proxy:        false
    user:             "{{ elasticsearch_username }}"
    password:         "{{ elasticsearch_password }}"
    ca_path:          "{{ ssl_ca_path }}"
    method:           POST
    src:              "files/security_role_mappings/{{ item.mapping_name }}.json"
    body_format:      json
    force_basic_auth: yes
  become: "{{ become_root }}"
  loop: "{{ elasticsearch_security_role_mappings_list }}"
###
  
