###
# Prepare base
##
- name: Import elastic-templates secrets
  include_vars: "inventories/{{ deployment_environment }}/group_vars/elastic_templates/secrets.yml"
  no_log:       true

- name: Import elastic-nodes secrets
  include_vars: "inventories/{{ deployment_environment }}/group_vars/elastic_nodes/vars.yml"
  no_log:       true
###


###
# Import Index Templates
##
- name: Import Index Templates
  uri: 
    url:              "https://{{ elastic_publish_host }}:61116/_template/{{ item.index_template_name }}"
    use_proxy:        false
    user:             "{{ elasticsearch_username }}"
    password:         "{{ elasticsearch_password }}"
    ca_path:          "{{ ssl_ca_path }}"
    method:           PUT
    src:              "files/index_templates/{{ item.index_template_name }}.json"
    body_format:      json
    force_basic_auth: yes
  become: "{{ become_root }}"
  loop: "{{ elasticsearch_index_template_list }}"
###
