###
# Prepare base
##
- name: Import secrets
  include_vars: "inventories/{{ deployment_environment }}/group_vars/elasticsearch_rolling_upgrade/secrets.yml"
  no_log:       true

- name: Import secrets
  include_vars: "inventories/{{ deployment_environment }}/group_vars/elastic_nodes/vars.yml"
  no_log:       true
###


###
# Full scale upgrade strategy
##
# Same as manually executing `docker-compose down -v`
- name: Destroy existing Elasticsearch container
  community.docker.docker_compose:
    project_src:    "{{ elastic_dir }}"
    state:          absent
    remove_volumes: true
  become: "{{ become_root }}"

- name: Wait for 2 minutes while Elasticsearch container are being destroyed
  pause:
    minutes: 2

# Same as manually executing `docker-compose up -d`
- name: Create fresh Elasticsearch container
  community.docker.docker_compose:
    project_src:    "{{ elastic_dir }}"
    state:          present
  become: "{{ become_root }}"
###
